POST http://localhost:8080/api/user/register HTTP/1.1
content-type: application/json

{
    "login": "ale",
    "password": "12345"
}

###

POST http://localhost:8080/api/user/register HTTP/1.1
content-type: application/json

{
    "login": "kate",
    "password": "7777"
}

###

POST http://localhost:8080/api/user/login HTTP/1.1
content-type: application/json

{
    "login": "ale",
    "password": "12345"
}

###

POST http://localhost:8080/invoice HTTP/1.1
content-type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZXhwIjoxNzA0NzMyNDI5LCJpYXQiOjE3MDQ3MzA2Mjl9.IiJ9TvXXhXbI9KwX-AngHZnefmtWR4g-dJTDZ0BG5Ag

{
    "currency": "USD",
    "amount": 15,
    "wallet_number" : "321"
}

###

POST http://localhost:8080/invoice HTTP/1.1
content-type: application/json
Cookie:token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZXhwIjoxNzA0NzM5MDU2LCJpYXQiOjE3MDQ3MzcyNTZ9.5JT9NPS7X8t-a1_RIFTnHrnlpxSbUfq44yUnfBY3rSA

{
    "currency": "USD",
    "amount": 0.0000000000000000000000000123,
    "wallet_number" : "321"
}

###

POST http://localhost:8080/withdraw HTTP/1.1
content-type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZXhwIjoxNzA0NzM5MDU2LCJpYXQiOjE3MDQ3MzcyNTZ9.5JT9NPS7X8t-a1_RIFTnHrnlpxSbUfq44yUnfBY3rSA

{
    "currency": "SEK",
    "amount": 0.0000123,
    "wallet_number" : "123"
}

###

GET http://localhost:8080/balance/actual HTTP/1.1
content-type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZXhwIjoxNzA0NzM5MDU2LCJpYXQiOjE3MDQ3MzcyNTZ9.5JT9NPS7X8t-a1_RIFTnHrnlpxSbUfq44yUnfBY3rSA

###

GET http://localhost:8080/balance/frozen HTTP/1.1
content-type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZXhwIjoxNzA0NzM5MDU2LCJpYXQiOjE3MDQ3MzcyNTZ9.5JT9NPS7X8t-a1_RIFTnHrnlpxSbUfq44yUnfBY3rSA